// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1563891067);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1563891307);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1563891187);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 655360);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1563891036);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{be0eba36-f35c-40a8-9280-52b107815df4}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1563891067497");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1563894667497");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190706110151");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1563891038");
user_pref("browser.slowStartup.averageTime", 1762);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190706110151");
user_pref("browser.startup.homepage_override.mstone", "68.0");
user_pref("browser.startup.lastColdStartupCheck", 1563891037);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "e908b7510fbe477386b596449b442c78");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.0");
user_pref("extensions.lastPlatformVersion", "68.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"af67177e-8778-4e1c-bd5b-11df4ffc3077\",\"fxmonitor@mozilla.org\":\"a484776c-82f3-48ce-b68e-6ce6d16cad42\",\"screenshots@mozilla.org\":\"55ccef3e-6f73-423a-bb2b-b608fc32527c\",\"webcompat-reporter@mozilla.org\":\"cd8b4649-86eb-41ac-aeb2-ca18277c96ba\",\"webcompat@mozilla.org\":\"6f26b10d-6ad7-45ae-b829-1f64cae849fd\",\"google@search.mozilla.org\":\"373289a0-ce60-45a2-ab6e-d2e8c5ccb473\",\"amazondotcom@search.mozilla.org\":\"04f50eb0-81bc-45c8-88eb-60f02f728ac4\",\"bing@search.mozilla.org\":\"78a8f467-15b8-4491-a113-56972a832eb8\",\"ddg@search.mozilla.org\":\"399ecdce-8abf-4806-9896-944c3f14b1f6\",\"ebay@search.mozilla.org\":\"4cbd2194-d7c5-4f65-8642-27b575e43b30\",\"twitter@search.mozilla.org\":\"15de2940-6e6e-4867-9fe2-1e8a8440572c\",\"wikipedia@search.mozilla.org\":\"34e38155-4c4f-4130-951d-57ac1fb03c5f\",\"default-theme@mozilla.org\":\"86c75fe2-e5a4-4bd7-b573-54699afa7c02\"}");
user_pref("media.gmp-manager.buildID", "20190706110151");
user_pref("media.gmp-manager.lastCheck", 1563891173);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "152dbcbe-b8cf-4a52-a225-e54cf7ed42d6");
user_pref("security.sandbox.plugin.tempDirSuffix", "4c20da51-266f-4a0a-8582-8b7669c6d22a");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1563891035);
user_pref("toolkit.telemetry.cachedClientID", "d5f8abaa-4e61-4261-98df-50d4c55c5f5c");
user_pref("toolkit.telemetry.previousBuildID", "20190706110151");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
