#
# Defines environment variables.
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

export PAGER='less'
export EDITOR='vim'
export VISUAL='vim'

export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
  $HOME/.local/bin
  $HOME/.cargo/bin
  $HOME/go/bin
)

# Set the default Less options.
export LESS='-g -i -M -R -w -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
