#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source "$HOME/.aliases"
source "$HOME/.functions"

export HISTFILE="$HOME/.zsh_history"
export PIPENV_VENV_IN_PROJECT=true

autoload -U promptinit; promptinit
prompt spaceship

SPACESHIP_CHAR_SYMBOL='൧ '
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_GIT_BRANCH_PREFIX=" "

SPACESHIP_PROMPT_ORDER=(user host dir git venv pyenv ruby node exec_time line_sep char)
