#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source "$HOME/.aliases"
source "$HOME/.functions"

export HISTFILE="$HOME/.zsh_history"
export WORKON_HOME=$HOME/.virtualenvs
export HOMEBREW_NO_AUTO_UPDATE=1


source "$HOME/repos/spaceship-prompt/spaceship.zsh"
SPACESHIP_CHAR_COLOR_SUCCESS='magenta'
SPACESHIP_CHAR_COLOR_FAILURE='red'
SPACESHIP_TIME_SHOW=true

SPACESHIP_PACKAGE_SYMBOL=''
SPACESHIP_DIR_LOCK_SYMBOL=''

SPACESHIP_PROMPT_ORDER=(user host dir git venv python package exec_time line_sep jobs char)
SPACESHIP_RPROMPT_ORDER=(time)

function set-title-precmd() {
  printf "\e]2;%s\a" "${PWD/#$HOME/~}"
}

function set-title-preexec() {
  printf "\e]2;%s\a" "$1"
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd set-title-precmd
add-zsh-hook preexec set-title-preexec

source ~/.local/bin/virtualenvwrapper_lazy.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
